NTEE = {
    "ARTES, CULTURA Y HUMANIDADES": {
        "A01":	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "A02":	 "Asistencia Técnica y Administración",
        "A03":	 "Asociaciones y Sociedades Profesionales",
        "A05":	 "Institutos de Investigación y/o Análisis de Políticas Públicas",
        "A11":	 "Patronato Dedicado a Organización Única",
        "A12":	 "Distribución y Recaudación de Fondos/Donativos",
        "A19":	 "Apoyo (sin clasificación específica)",
        "A20":	 "Arte y cultura",
        "A23":	 "Concientización cultural/étnica",
        "A24":	 "Artes folclóricas",
        "A25":	 "Educación del arte",
        "A26":	 "Consejos y agencias de artes y humanidades",
        "A27":	 "Promoción y Producción de Eventos y Festejos Comunitarios",
        "A30":	 "Medios y Comunicación",
        "A31":	 "Cine y video",
        "A32":	 "Televisión",
        "A33":	 "Publicaciones ",
        "A34":	 "Radio",
        "A40":	 "Artes visuales",
        "A50":	 "Museos",
        "A51":	 "Museos de arte",
        "A52":	 "Museos para niños",
        "A54":	 "Museos de historia",
        "A56":	 "Museos de historia natural y de ciencia natural",
        "A57":	 "Museos de ciencia y tecnología",
        "A60":	 "Artes escénicas",
        "A61":	 "Centros de artes escénicas",
        "A62":	 "Baile",
        "A63":	 "Ballet",
        "A65":	 "Teatro",
        "A68":	 "Música",
        "A69":	 "Orquestas sinfónicas",
        "A6A":	 "Opera",
        "A6B":	 "Grupos de coro y canto",
        "A6C":	 "Bandas y ensambles musicales",
        "A6E":	 "Escuelas de artes escénicas",
        "A70":	 "Humanidades",
        "A80":	 "Organizaciones históricas",
        "A82":	 "Sociedades históricas y de preservación histórica",
        "A84":	 "Eventos conmemorativos",
        "A90":	 "Servicios de arte",
        "A99":	 "Arte, cultura y humanidades (sin clasificación específica)"},
    "EDUCACIÓN": {
        "B01":	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "B02":	 "Asistencia Técnica y Administración",
        "B03":	 "Asociaciones y Sociedades Profesionales",
        "B05":	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "B11":	 "Patronato Dedicado a Organización Única",
        "B12":	 "Distribución y Recaudación de Fondos/Donativos",
        "B19":	 "Apoyo (sin clasificación específica)",
        "B20":	 "Escuelas de educación  primaria y secundaria",
        "B21":	 "Pre-primarias",
        "B24":	 "Escuelas primarias",
        "B25":	 "Escuelas secundarias y preparatorias",
        "B28":	 "Educación especial",
        "B29":	 "Charter schools (no existe en México)",
        "B30":	 "Escuelas técnicas y  vocacionales",
        "B40":	 "Educación superior",
        "B41":	 "Community/Junior colleges (no existe en México)",
        "B42":	 "Undergraduate colleges (no existe en México)",
        "B43":	 "Universidades",
        "B50":	 "Escuelas profesionales",
        "B60":	 "Educación para adultos",
        "B70":	 "Bibliotecas",
        "B80":	 "Servicios para estudiantes",
        "B82":	 "Becas y apoyo financiero",
        "B83":	 "Fraternidades y hermandades",
        "B84":	 "Asociaciones de alumnos",
        "B90":	 "Otros Servicios educacionales",
        "B92":	 "Grupos de lectura",
        "B94":	 "Grupos para maestros y padres de familia",
        "B99":	 "Educación (sin clasificación específica)"},
    "MEDIO AMBIENTE": {
        "C01":	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "C02":	 "Asistencia Técnica y Administración",
        "C03":	 "Asociaciones y Sociedades Profesionales",
        "C05":	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "C11":	 "Patronato Dedicado a Organización Única",
        "C12":	 "Distribución y Recaudación de Fondos/Donativos",
        "C19":	 "Apoyo (sin clasificación específica)",
        "C20":	 "Control y combate de la contaminación",
        "C27":	 "Reciclaje",
        "C30":	 "Conservación y protección de los recursos naturales",
        "C32":	 "Recursos hidrológicos",
        "C34":	 "Conservación orográfica",
        "C35":	 "Desarrollo y conservación de recursos energéticos",
        "C36":	 "Conservación forestal",
        "C40":	 "Servicios de horticultura, botánica y paisaje",
        "C41":	 "Jardines botánicos",
        "C42":	 "Clubes botánicos",
        "C50":	 "Embellecimiento ambiental",
        "C60":	 "Educación ambiental",
        "C99":	 "Medio ambiente (sin clasificación específica)"},
    "RELATIVO A LOS ANIMALES": {
        "D01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "D02": 	 "Asistencia Técnica y Administración",
        "D03": 	 "Asociaciones y Sociedades Profesionales",
        "D05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "D11": 	 "Patronato Dedicado a Organización Única",
        "D12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "D19": 	 "Apoyo (sin clasificación específica)",
        "D20": 	 "Cuidado y protección animal",
        "D30": 	 "Protección y conservación de la vida animal salvaje",
        "D31": 	 "Protección a especies en peligro de extinción",
        "D32": 	 "Santuarios para aves",
        "D33": 	 "Pesquería",
        "D34": 	 "Santuarios para animales salvajes",
        "D40": 	 "Servicios veterinarios",
        "D50": 	 "Zoológicos",
        "D60": 	 "Servicios animales (sin clasificación específica)",
        "D61": 	 "Entrenamiento para animales/comportamiento",
        "D99": 	 "Relativo a los animales (sin clasificación específica)"},
    "SALUD": {
        "E01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "E02": 	 "Asistencia Técnica y Administración",
        "E03": 	 "Asociaciones y Sociedades Profesionales",
        "E05": 	 "Institutos de Investigación y Análisis de Políticas Públicas ",
        "E11": 	 "Patronato Dedicado a Organización Única",
        "E12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "E19": 	 "Apoyo (sin clasificación específica)",
        "E20": 	 "Hospitales",
        "E21": 	 "Sistemas de salud pública comunita-rios",
        "E22": 	 "Hospitales generales",
        "E24": 	 "Hospitales de especialidades",
        "E30": 	 "Salud primaria y ambulatoria",
        "E31": 	 "Prácticas de salud grupales",
        "E32": 	 "Clínicas comunitarias",
        "E40": 	 "Salud de reproducción",
        "E42": 	 "Planificación familiar",
        "E50": 	 "Rehabilitación",
        "E60": 	 "Apoyo médico",
        "E61": 	 "Bancos de sangre",
        "E62": 	 "Servicios de urgencia y transporte",
        "E65": 	 "Bancos de órganos y tejidos",
        "E70": 	 "Programas de Salud Pública",
        "E80": 	 "Salud (general y financiamiento)",
        "E86": 	 "Apoyo al paciente y a su familia",
        "E90": 	 "Enfermería",
        "E91": 	 "Instalaciones de enfermería",
        "E92": 	 "Cuidados domésticos",
        "E99": 	 "Salud (sin clasificación específica)"},
    "SALUD MENTAL": {
        "F01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "F02": 	 "Asistencia Técnica y Administración",
        "F03": 	 "Asociaciones y Sociedades Profesionales",
        "F05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "F11": 	 "Patronato Dedicado a Organización Única",
        "F12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "F19": 	 "Apoyo (sin clasificación específica)",
        "F20": 	 "Tratamiento y prevención a la dependencia de substancias",
        "F21": 	 "Prevención al abuso de substancias",
        "F22": 	 "Tratamiento al abuso de substancias",
        "F30": 	 "Tratamiento psicológico",
        "F31": 	 "Hospitales psiquiátricos",
        "F32": 	 "Centros de salud mental pública",
        "F33": 	 "Residencias para tratamiento psiquiá-trico",
        "F40": 	 "Intervención en crisis y apoyo telefónico (teléfono rojo)",
        "F42": 	 "Servicios para abuso sexual",
        "F50": 	 "Desórdenes psicológicos (sin clasificación específica)",
        "F52": 	 "Tabaquismo",
        "F53": 	 "Desórdenes alimenticios y adicciones",
        "F54": 	 "Adicciones al juego/apuestas",
        "F60": 	 "Terapia",
        "F70": 	 "Desórdenes mentales",
        "F80": 	 "Asociaciones para la salud mental",
        "F99": 	 "Salud mental e intervención en crisis (sin clasificación específica)"},
    "ENFERMEDADES, DESÓRDENES Y DISCIPLINAS MÉDICAS": {
        "G01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "G02": 	 "Asistencia Técnica y Administración",
        "G03": 	 "Asociaciones y Sociedades Profesionales",
        "G05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "G11": 	 "Patronato Dedicado a Organización Única",
        "G12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "G19": 	 "Apoyo (sin clasificación específica)",
        "G20": 	 "Enfermedades Genéticas, Malformaciones Congénitas",
        "G25": 	 "Síndrome de Down",
        "G30": 	 "Cáncer",
        "G40": 	 "Enfermedades de Órganos Específicos",
        "G41": 	 "Enfermedades Visuales, Ceguera, e Impedimento Visual",
        "G42": 	 "Enfermedades de Garganta y Oído",
        "G43": 	 "Enfermedades y Desórdenes del Corazón y Sistema Circulatorio",
        "G44": 	 "Enfermedades del Riñón",
        "G45": 	 "Enfermedades de Pulmón",
        "G48": 	 "Desórdenes Cerebrales",
        "G50": 	 "Enfermedades Musculares, Nerviosas u Óseas",
        "G51": 	 "Artritis",
        "G54": 	 "Epilepsía",
        "G60": 	 "Enfermedades Relacionadas a Alergías",
        "G61": 	 "Asma",
        "G70": 	 "Desórdenes y Enfermedades Digestivas",
        "G80": 	 "Enfermedades Específicas",
        "G81": 	 "VIH/SIDA",
        "G83": 	 "Alzeheimer's",
        "G84": 	 "Autismo",
        "G90": 	 "Disciplinas Médicas",
        "G92": 	 "Bioingeniería y Ciencias Biomédi-cas",
        "G94": 	 "Geriátrica",
        "G96": 	 "Neurología y Neurociencias",
        "G98": 	 "Pediatría",
        "G99":   "Desórdenes, Enfermedades, Disciplinas Médicas (Sin Clasificación Específica)",
        "G9B": 	 "Especialidades Quirúrgicas"},
    "INVESTIGACIÓN MÉDICA": {
        "H01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "H02": 	 "Asistencia Técnica y Administración",
        "H03": 	 "Asociaciones y Sociedades Profesionales",
        "H05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "H11": 	 "Patronato Dedicado a Organización Única",
        "H12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "H19": 	 "Apoyo (sin clasificación específica)",
        "H20": 	 "Investigación de Enfermedades Genéticas y Malformacio-nes Congénitas",
        "H25": 	 "Investigación del Síndrome de Down",
        "H30": 	 "Investigación sobre el Cáncer",
        "H32": 	 "Investigación sobre el Cáncer de Mama",
        "H40": 	 "Investigación sobre Órganos Específicos",
        "H41": 	 "Investigación sobre Enfermedades Visuales, Ceguera, e Impedimento Visual",
        "H42": 	 "Investigación sobre Enfermedades de Oído y Garganta",
        "H43": 	 "Investigación sobre Enfermedades y Desórdenes del Corazón y Siste-ma Circulatorio",
        "H44": 	 "Investigación sobre Enfermedades del Riñón",
        "H45": 	 "Investigación sobre Enfermedades de Pulmón",
        "H48": 	 "Investigación sobre Desórdenes Cerebrales",
        "H50": 	 "Investigación de Enfermedades Musculares, Nerviosas u Óseas",
        "H51": 	 "Investigación del Artritis",
        "H54": 	 "Investigación de Epilepsia",
        "H60": 	 "Investigación de Enfermedades Relacionadas a Alergias",
        "H61": 	 "Investigación del Asma",
        "H70": 	 "Investigación de Desórdenes y Enfermedades Digestivas",
        "H80": 	 "Investigación de Enfermedades Específicas",
        "H81": 	 "Investigación del VIH/SIDA",
        "H83": 	 "Investigación del Alzeheimer's",
        "H84": 	 "Investigación del Autismo",
        "H90": 	 "Investigación de Especialida-des Médicas",
        "H92": 	 "Investigación de Bioingeniería y Ciencias Biomédicas",
        "H94": 	 "Investigación Geriátrica",
        "H96": 	 "Investigación de Neurología y Neurociencias",
        "H98": 	 "Investigación Pediátrica",
        "H99": 	 "Otras Investigaciones Médicas Sin Clasificación Especial",
        "H9B": 	 "Investigación de Especialidades Quirúrgicas"},
    "RELACIONADOS A ASUNTOS JURÍDICOS Y  CRIMINALÍSTICOS": {
        "I01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "I02": 	 "Asistencia Técnica y Administra-ción",
        "I03":  	" Asociaciones y Sociedades Profesionales",
        "I05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "I11": 	 "Patronato Dedicado a Organización Única",
        "I12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "I19": 	 "Apoyo (sin clasificación específica)",
        "I20": 	 "Prevención de Crimen",
        "I21": 	 "Prevención de Delincuencia Juvenil",
        "I23": 	 "Relacionadas a Conducir bajo Efectos del Alcohol",
        "I30": 	 "Prisiones/Centros Correccionales",
        "I31": 	 "Atención durante Proceso de Reintegración, Casas de Transición para Ex-Delincuentes",
        "I40": 	 "Servicios de Rehabilitación para Delincuentes",
        "I43": 	 "Servicios a Prisioneros y Familiares",
        "I44": 	 "Alternativas a Prisión",
        "I50": 	 "Administración de Justicia y Cortes (Administración de la Corte, Reformas, Alternativas de Litigación y Sentencia)",
        "I51": 	 "Resolución de Disputas/Servicios de Mediación",
        "I60": 	 "Agencias del Orden Público (Departamentos Policiales)",
        "I70": 	 "Protección y Prevención en Contra de Abandono, Abuso y Explotación",
        "I71": 	 "Prevención de Abuso Doméstico",
        "I72": 	 "Prevención de Abuso a Menores",
        "I73": 	 "Prevención de Abuso Sexual",
        "I80": 	 "Servicios Legales",
        "I83": 	 "Litigio/Ley de Interés Público"},
    "RELACIONADAS AL EMPLEO": {
        "J01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "J02": 	 "Asistencia Técnica y Administración",
        "J03": 	 "Asociaciones y Sociedades Profesionales",
        "J05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "J11": 	 "Patronato Dedicado a Organización Única",
        "J12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "J19": 	 "Apoyo (sin clasificación específica)",
        "J20": 	 "Asistencia para Capacitación Laboral y Obtención de Empleo ",
        "J21": 	 "Orientación y Pruebas Vocacionales",
        "J22": 	 "Capacitación Laboral",
        "J30": 	 "Rehabilitación Vocacional (Capacitación Laboral y Obtención de Empleo para los Discapacitados y Personas de Tercera Edad)",
        "J32": 	 "Industrias de Buena Voluntad",
        "J33": 	 "Centro de Actividades Laborales, Talleres de Trabajo para Personas con Capacidades Diferentes Sin Clasificación Específica",
        "J40": 	 "Organizaciones/Sindicatos Laborales",
        "J99": 	 "Relacionadas al Empleo Sin Clasificación Específica"},
    "AGRICULTURA, COMIDA Y NUTRICIÓN": {
        "K01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "K02": 	 "Asistencia Técnica y Administración",
        "K03": 	 "Asociaciones y Sociedades Profesionales",
        "K05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "K11": 	 "Patronato Dedicado a Organización Única",
        "K12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "K19": 	 "Apoyo (sin clasificación específica)",
        "K20": 	 "Programas Agrarios",
        "K25": 	 "Preservación de Tierras Arables",
        "K26": 	 "Cría, Desarrollo y Manutención de Ganado",
        "K28": 	 "Agencias de Promoción de Agricultura",
        "K30": 	 "Programas de Distribución de Comida Gratuita, Servicios Alimenticios",
        "K31": 	 "Banco de Alimentos, Despensas Alimenticias",
        "K34": 	 "Preparación y Asistencia Alimentaria a Grupos",
        "K35": 	 "Cafetería o Agencia Patrocinada por Organizaciones",
        "K36": 	 "Servicio Domiciliario de Comidas Preparadas",
        "K40": 	 "Programas de Nutrición",
        "K50": 	 "Economía Doméstica",
        "K99": 	 "Otras Organizaciones de Agricultura, Comida, Nutrición Sin Clasificación Específica"},
    "VIVIENDAS, ALBERGUES": {
        "L01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "L02": 	 "Asistencia Técnica y Administración",
        "L03": 	 "Asociaciones y Sociedades Profesionales",
        "L05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "L11": 	 "Patronato Dedicado a Organización Única",
        "L12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "L19": 	 "Apoyo (sin clasificación específica)",
        "L20": 	 "Desarrollo, Construcción y Administración de Viviendas",
        "L21": 	 "Viviendas Públicas",
        "L22": 	 "Comunidades de Retiro, Viviendas para Personas de la Tercera Edad",
        "L24": 	 "Viviendas Independientes para Personas con Capacidades Diferentes",
        "L25": 	 "Programas de Rehabilitación/Renovación de Viviendas",
        "L30": 	 "Asistencia en Búsqueda de Vivienda",
        "L40": 	 "Vivienda Temporal de Bajo Costo",
        "L41": 	 "Albergues Temporales para los Indigentes",
        "L50": 	 "Organizaciones de Dueños o Arrendatarios de Viviendas",
        "L80": 	 "Otros Servicios de Apoyo de Vivienda",
        "L81": 	 "Organizaciones de Reparación o Bricolaje de Viviendas",
        "L82": 	 "Asistencia con Pago de Rentas, Apoyo para Reducción de Gastos de Vivienda",
        "L99": 	 "Otras organizaciones de "},
    "SEGURIDAD PÚBLICA, PREPARACIÓN EN CASO DE DESASTRES NATURALES Y APOYO A DAMNIFICADOS": {
        "M01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "M02": 	 "Asistencia Técnica y Administración",
        "M03": 	 "Asociaciones y Sociedades Profesionales",
        "M05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "M11": 	 "Patronato Dedicado a Organización Única",
        "M12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "M19": 	 "Apoyo (sin clasificación específica)",
        "M20": 	 "Protección civil en Caso de Desastres",
        "M23": 	 "Escuadras de búsqueda y rescate",
        "M24": 	 "Prevención de incendios",
        "M40": 	 "Educación de seguridad",
        "M41": 	 "Primeros auxilios",
        "M42": 	 "Seguridad al volante",
        "M60": 	 "Asociaciones de benevolencia para la seguridad pública",
        "M99": 	 "Seguridad Pública, Preparación en Caso de Desastres y Apoyo a Damnificados (sin clasificación específica)"},
    "RECREACIÓN Y DEPORTES": {
        "N01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "N02": 	 "Asistencia Técnica y Administración",
        "N03": 	 "Asociaciones y Sociedades Profesionales",
        "N05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "N11": 	 "Patronato Dedicado a Organización Única",
        "N12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "N19": 	 "Apoyo (sin clasificación específica)",
        "N20": 	 "Canchas",
        "N30": 	 "Educación física e instalaciones públicas para la recrea-ción",
        "N31": 	 "Centros de recreación pública/comunitaria",
        "N32": 	 "Parques y patios de recreo",
        "N40": 	 "Asociaciones deportivas y lugares de entrenamiento",
        "N50": 	 "Clubes recreativas",
        "N52": 	 "Ferias y festivales",
        "N60": 	 "Deportes (amateur)",
        "N61": 	 "Pesca y caza",
        "N62": 	 "Basketball",
        "N63": 	 "Beisbol",
        "N64": 	 "Fútbol soccer",
        "N65": 	 "Fútbol americano",
        "N66": 	 "Deportes con raqueta",
        "N67": 	 "Natación y otras actividades acuáticas",
        "N68": 	 "Deportes de invierno",
        "N69": 	 "Ecuestres",
        "N6A": 	 "Golf",
        "N70": 	 "Competencias deportivas (amateur)",
        "N71": 	 "Olimpiadas",
        "N72": 	 "Olimpiadas especiales",
        "N80": 	 "Ligas atléticas profesionales",
        "N99": 	 "Recreación y deportes (sin clasificación específica)"},
    "DESARROLLO JUVENIL": {
        "O01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "O02": 	 "Asistencia Técnica y Administr",
        "O03": 	 "Asociaciones y Sociedades Prof",
        "O05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "O11": 	 "Patronato Dedicado a Organización Única",
        "O12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "O19": 	 "Apoyo (sin clasificación específica)",
        "O20": 	 "Centros y clubes juveniles",
        "O21": 	 "Clubes de niños",
        "O22": 	 "Clubes de niñas",
        "O23": 	 "Clubes de niños y de niñas",
        "O30": 	 "Programas de Mentores Adultos/Menores Sin Clasificación Específica",
        "O31": 	 "Programa de Mentores 'Big brothers and big sisters'",
        "O40": 	 "Organizaciones de exploradores (scouts)",
        "O41": 	 "Niños exploradores (scouts)",
        "O42": 	 "Niñas exploradoras (scouts)",
        "O43": 	 "Campamentos",
        "O50": 	 "Programas para el desarrollo juvenil",
        "O51": 	 "Clubes públicos para el servicio a los jóvenes",
        "O52": 	 "Desarrollo juvenil - agricultura",
        "O53": 	 "Desarrollo juvenil - administración",
        "O54": 	 "Desarrollo juvenil - educación cívica",
        "O55": 	 "Desarrollo juvenil - religión",
        "O99": 	 "Desarrollo Juvenil (sin clasificación específica)"},
    "SERVICIOS HUMANOS": {
        "P01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "P02": 	 "Asistencia Técnica y Administración",
        "P03": 	 "Asociaciones y Sociedades Profesionales",
        "P05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "P11": 	 "Patronato Dedicado a Organización Única",
        "P12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "P19": 	 "Apoyo (sin clasificación específica)",
        "P20": 	 "Servicios humanos",
        "P21": 	 "Cruz Roja",
        "P22": 	 "Liga Urbana",
        "P24": 	 "Ejército de Salvación",
        "P26": 	 "Volunteers of America (no existe en México)",
        "P27": 	 "YMCA, YWCA,",
        "P28": 	 "Asociación de colonos",
        "P29": 	 "Tiendas de ahorro",
        "P30": 	 "Servicios para niños y jóvenes",
        "P31": 	 "Adopción",
        "P32": 	 "Cuidado temporal",
        "P33": 	 "Guarderia",
        "P40": 	 "Servicios familiares",
        "P42": 	 "Agencias para padres solteros",
        "P43": 	 "Refugios en caso de violencia familiar",
        "P44": 	 "Asistencia en el hogar",
        "P45": 	 "Servicios familiares para padres adolescentes",
        "P46": 	 "Terapia familiar",
        "P47": 	 "Centros de Acogida a Mujeres Embarazadas",
        "P50": 	 "Servicios sociales personales",
        "P51": 	 "Asesoría financiera",
        "P52": 	 "Asistencia para transporte",
        "P58": 	 "Distribución de regalos",
        "P60": 	 "Asistencia de urgencias",
        "P61": 	 "Ayuda al viajero",
        "P62": 	 "Servicios a víctimas",
        "P70": 	 "Servicios para personas de la tercera edad",
        "P71": 	 "Centros para personas de la tercera edad",
        "P73": 	 "Casas hogares",
        "P74": 	 "Hospicios",
        "P75": 	 "Residencias con apoyo para personas de la tercera edad",
        "P80": 	 "Centros de apoyo para la independencia de sectores específicos",
        "P81": 	 "Centros para personas de la tercera edad",
        "P82": 	 "Centros para personas con capacidades diferentes",
        "P84": 	 "Centros para minorías étnicas e inmigrantes",
        "P85": 	 "Centros para personas sin hogar",
        "P86": 	 "Centros para ciegos y personas con impedimentos visuales",
        "P87": 	 "Centros para sordos y personas con impedimentos auditivos",
        "P88": 	 "Centros para LGTB",
        "P99": 	 "Servicios humanos (sin clasificación específica)"},
    "ASUNTOS DE POLÍTICA Y  SEGURIDAD INTERNACIONAL": {
        "Q01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "Q02": 	 "Asistencia Técnica y Administración",
        "Q03": 	 "Asociaciones y Sociedades Profesionales",
        "Q05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "Q11": 	 "Patronato Dedicado a Organización Única",
        "Q12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "Q19": 	 "Apoyo (sin clasificación específica)",
        "Q20": 	 "Creación de lazos internacionales",
        "Q21": 	 "Intercambios culturales internacionales",
        "Q22": 	 "Intercambios académicos internacionales",
        "Q23": 	 "Intercambio internacional (sin clasificación específica)",
        "Q30": 	 "Desarrollo internacional",
        "Q31": 	 "Desarrollo agrícola internacional",
        "Q32": 	 "Desarrollo económico internacional",
        "Q33": 	 "Ayuda internacional",
        "Q35": 	 "Desarrollo de la sociedad civil y de la democracia",
        "Q40": 	 "Seguridad y paz internacional",
        "Q41": 	 "Control de armas y paz",
        "Q42": 	 "Asociaciones de naciones unidas",
        "Q43": 	 "Seguridad nacional",
        "Q50": 	 "Asuntos internacionales, globalización, y políticas internacionales",
        "Q51": 	 "Política económica y de comercio",
        "Q70": 	 "Derechos humanos internacionales",
        "Q71": 	 "Migración y refugiados",
        "Q99": 	 "Asuntos, política y seguridad internacional (sin clasificación específica)"},
    "Derechos cíviles y acción social": {
        "R01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "R02": 	 "Asistencia Técnica y Administración",
        "R03": 	 "Asociaciones y Sociedades Profesionales",
        "R05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "R11": 	 "Patronato Dedicado a Organización Única",
        "R12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "R19": 	 "Apoyo (sin clasificación específica)",
        "R20": 	 "Derechos civiles",
        "R22": 	 "Derechos de las minorías",
        "R23": 	 "Derechos de personas con capacidades especiales",
        "R24": 	 "Derechos de las mujeres",
        "R25": 	 "Derechos de las personas de la tercera edad",
        "R26": 	 "Derechos de los LGTB",
        "R28": 	 "Derechos de los niños",
        "R30": 	 "Relaciones Multiculturales e Intergrupales",
        "R40": 	 "Educación a los votantes",
        "R60": 	 "Libertades civiles",
        "R61": 	 "Derechos Reproductivos",
        "R62": 	 "Derecho a la vida",
        "R63": 	 "Censura y libertad de prensa y expresión",
        "R67": 	 "Derecho a la muerte y eutanasia",
        "R99": 	 "Derechos civiles, acción y promoción social (sin clasificación específica)"},
    "MEJORAS Y DESARROLLO PARA LA COMUNIDAD": {
        "S01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "S02": 	 "Asistencia Técnica y Administración",
        "S03": 	 "Asociaciones y Sociedades Profesionales",
        "S05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "S11": 	 "Patronato Dedicado a Organización Única",
        "S12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "S19": 	 "Apoyo (sin clasificación específica)",
        "S20": 	 "Desarrollo de la comunidad y la colonia",
        "S21": 	 "Coaliciones comunitarias",
        "S22": 	 "Associaciones de colonos",
        "S30": 	 "Desarrollo económico",
        "S31": 	 "Desarrollo económico urbano",
        "S32": 	 "Desarrollo económico rural",
        "S40": 	 "Industria y comercio",
        "S41": 	 "Cámaras de comercio y ligas de negocio",
        "S43": 	 "Desarrollo de pequeñas empresas",
        "S46": 	 "Consejos de comercio",
        "S47": 	 "Asociaciones de bienes raíces",
        "S50": 	 "Gestión sin fines de lucro",
        "S80": 	 "Clubes al servicio de la comunidad",
        "S81": 	 "Clubes de mujeres al servicio de la comunidad",
        "S82": 	 "Clubes de hombres al servicio de la comunidad",
        "S99": 	 "Mejoras y desarrollo para la comunidad (sin clasificación específica)"},
    "FILANTROPÍA, VOLUNTARIA-DO Y FUNDACIONES DONANTES": {
        "T01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "T02": 	 "Asistencia Técnica y Administración",
        "T03": 	 "Asociaciones y Sociedades Profesionales",
        "T05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "T11": 	 "Patronato Dedicado a Organización Única",
        "T12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "T19": 	 "Apoyo (sin clasificación específica)",
        "T20": 	 "Fundaciones donantes privadas",
        "T21": 	 "Fundaciones corporativas",
        "T22": 	 "Fundaciones independientes privadas",
        "T23": 	 "Fundaciones operativas privadas",
        "T30": 	 "Fundaciones públicas",
        "T31": 	 "Fundaciones comunitarias",
        "T40": 	 "Promoción del voluntariado",
        "T50": 	 "Promoción de la filantropía, la caridad y el voluntariado",
        "T70": 	 "Programas donantes federales",
        "T90": 	 "Fundaciones/Fideicomisos Nombrados Sin Clasificación Específica",
        "T99": 	 "Filantropía, voluntariado y fundaciones donantes (sin cla-sificación específica)"},
    "CIENCIA Y TECNOLOGÍA": {
        "U01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "U02": 	 "Asistencia Técnica y Administración",
        "U03": 	 "Asociaciones y Sociedades Profesionales",
        "U05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "U11": 	 "Patronato Dedicado a Organización Única",
        "U12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "U19": 	 "Apoyo (sin clasificación específica)",
        "U20": 	 "Ciencia en general",
        "U21": 	 "Ciencia marina y oceonografía",
        "U30": 	 "Ciencia físicas y de la tierra",
        "U31": 	 "Astronomía",
        "U33": 	 "Química e Ingeniería química",
        "U34": 	 "Matemáticas",
        "U36": 	 "Geología",
        "U40": 	 "Tecnología e ingeniería",
        "U41": 	 "Computación",
        "U42": 	 "Ingeniería",
        "U50": 	 "Ciencia biológicas",
        "U99": 	 "Ciencia y tecnología (sin clasificación específica)"},
    "CIENCIAS SOCIALES": {
        "V01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "V02": 	 "Asistencia Técnica y Administración",
        "V03": 	 "Asociaciones y Sociedades Profesionales",
        "V05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "V11": 	 "Patronato Dedicado a Organización Única",
        "V12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "V19": 	 "Apoyo (sin clasificación específica)",
        "V20": 	 "Ciencias sociales",
        "V21": 	 "Sociología y antropología",
        "V22": 	 "Economía",
        "V23": 	 "Ciencia de la conducta",
        "V24": 	 "Ciencia política",
        "V25": 	 "Estudios demográficos",
        "V26": 	 "Jurisprudencia y legal",
        "V30": 	 "Investigación interdisciplinaria",
        "V31": 	 "Estudios afroamericanos",
        "V32": 	 "Estudios de Género y la Mujer",
        "V33": 	 "Estudios étnicos",
        "V34": 	 "Estudios de Urbanismo",
        "V35": 	 "Estudios internacionales",
        "V36": 	 "Gerontología",
        "V37": 	 "Estudios laborales",
        "V99": 	 "Ciencias sociales (sin clasificación específica)"},
    "BENEFICIENCIAS SOCIALES Y PÚBLICAS": {
        "W01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "W02": 	 "Asistencia Técnica y Administración",
        "W03": 	 "Asociaciones y Sociedades Profesionales",
        "W05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "W11": 	 "Patronato Dedicado a Organización Única",
        "W12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "W19": 	 "Apoyo (sin clasificación específica)",
        "W20": 	 "Administración pública y gobierno",
        "W22": 	 "Financiamiento público, impuestos y política monetaria",
        "W24": 	 "Participación ciudadana",
        "W30": 	 "Organizaciones de vetarnos y militares",
        "W40": 	 "Transporte público",
        "W50": 	 "Telecomunicaciones",
        "W60": 	 "Instituciones financieras",
        "W61": 	 "Caja de ahorros",
        "W70": 	 "Desarrollo de liderazgo",
        "W80": 	 "Servicios públicos",
        "W90": 	 "Protección al consumidor",
        "W99": 	 "Beneficiencias sociales y públicas (sin clasificación específica)"},
    "RELACIONADO CON LA  RELIGIÓN": {
        "X01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "X02": 	 "Asistencia Técnica y Administración",
        "X03": 	 "Asociaciones y Sociedades Profesionales",
        "X05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "X11": 	 "Patronato Dedicado a Organización Única",
        "X12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "X19": 	 "Apoyo (sin clasificación específica)",
        "X20": 	 "Cristianismo",
        "X21": 	 "Protestantes",
        "X22": 	 "Católico romanos",
        "X30": 	 "Judaísmo",
        "X40": 	 "Islam",
        "X50": 	 "Budismo",
        "X70": 	 "Hinduismo",
        "X80": 	 "Medios y comunicaciones religiosos",
        "X81": 	 "Cine y video religioso",
        "X82": 	 "Televisión religiosa",
        "X83": 	 "Publicaciones religiosas",
        "X84": 	 "Radio religiosa",
        "X90": 	 "Coaliciones interreligiosas",
        "X99": 	 "Relacionado con la religión (sin clasificación específica)"},
    "BENEFICIO MUTUO Y POR MEMEBRESÍA": {
        "Y01": 	 "Organizaciones/Alianzas de Asesoramiento y Promoción",
        "Y02": 	 "Asistencia Técnica y Administración",
        "Y03": 	 "Asociaciones y Sociedades Profesionales",
        "Y05": 	 "Institutos de Investigación y Análisis de Políticas Públicas",
        "Y11": 	 "Patronato Dedicado a Organización Única",
        "Y12": 	 "Distribución y Recaudación de Fondos/Donativos",
        "Y19": 	 "Apoyo (sin clasificación específica)",
        "Y20": 	 "Proveedores de seguros (no médico) ",
        "Y22": 	 "Asociaciones benevolentes de seguros de vida, compañías de telefonía e irrigación, y comp-ñías similares",
        "Y23": 	 "Asociaciones y compañías de seguros mutuos",
        "Y24": 	 "Compensaciones suplementarias de pensiones",
        "Y25": 	 "Organizaciones de reaseguro para empleados patrocinado por el gobierno",
        "Y30": 	 "Fondos de pensión y retiro",
        "Y33": 	 "Asociaciones de fondo de retiro para maestros",
        "Y34": 	 "Fideicomisos de pensiones fundados por empleados",
        "Y35": 	 "Planes de pensión para varios empleados",
        "Y40": 	 "Sociedades fraternales",
        "Y41": 	 "Sociedades beneficiarias fraternales",
        "Y42": 	 "Sociedades fraternales domésticas",
        "Y43": 	 "Asociaciones de beneficiencia para empleados voluntarios no del gobierno",
        "Y44": 	 "Asociaciones de beneficiencia para empleados voluntarios del gobierno",
        "Y50": 	 "Cementerios",
        "Y99": 	 "Beneficio mutuo y por membresía (sin clasificación específica)"}}
